create Database pharmacy_db;
use pharmacy_db;
create table products(product_id int(5) Primary Key auto_increment, product char(30) NOT NULL,category char(20) NOT NULL,price decimal(20,2) NOT NULL,quantity int(5) NOT NULL,batch_no int(5) not null,expiry_date date not null);
create table p_db_users(username char (14) primary key,admin int(1)not null, password varchar(20) not null,f_name char(15) not null,l_name char(15) not null, others char(15),address char (30) not null,gender char(6) not null);
create table users_phone(phone_user char (14) not null,phone_number char(14) not null, foreign key(phone_user) references p_db_users(username));
create table expenses(expense_id int(10) primary key auto_increment,cost decimal(20,2) not null,description text Not null, Date_time DateTime not null, issued_by_user char(14) not null, foreign key(issued_by_user) references p_db_users(username));
create table invoice(invoice_id int (30) primary key auto_increment,date_time datetime not null,sale_income decimal(20,2) not null,invoice_content text not null, U_id char(14) not null, foreign key(U_id) references p_db_users(username));
create table daily_sale(days_date date primary key, amount decimal(20,2) default '0.00');
create table programdata(varname char(30) primary key, _value char(255));
insert into p_db_users values('deletedusers','0','deletedusers','deletedusers','deletedusers','deletedusers','deletedusers','deletedusers');
insert into p_db_users values('admin','1','admin','admin','admin','admin','admin','admin');

insert into products (product,category,price,quantity,batch_no,expiry_date) values("Albendazole Tablet, 400 mg","Medicine","2.50","200","77283",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Amino Acid Solution Injection","Medicine","24.75","200","23433",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("ECL Antacid Mixture","Medicine","20.0","200","98766",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("E-Panol","Medicine","13.0","200","34422",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Enacef 125","Medicine","10.0","200","45434",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Enaphage","Medicine","10.0","200","87567",now() + INTERVAL 1 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Enoral","Medicine","18.0","200","34331",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Envico","Medicine","15.0","200","45442",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Fluxamox 250","Medicine","17.0","200","23223",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Fluxamox 500","Medicine","21.0","200","11221",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Gastrone Suspension","Medicine","1.0","34","23222",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Glibenil","Medicine","9.0","200","77755",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Histazine","Medicine","11.0","200","55656",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Malar 2","Medicine","5.0","200","34221",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Malar 2 Suspension","Medicine","7.0","200","11223",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Fiesta Condom","Protective","70.0","200","12323",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Kiss Condom","Protective","100.0","200","90987",now() + INTERVAL 2 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Champion Condom","Protective","90.0","200","89987",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Durex Condom","Protective","50.0","200","70889",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Adutwumwaa Bitters","Herbal","39.0","200","78788",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Ebetoda Bitters","Herbal","32.0","200","78768",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Panadol 500mg","Medicine","1.50","200","66766",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Amlodipine","Medicine","11.0","200","45654",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Amoxicillin","Medicine","1.50","200","78876",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Atorvastatin","Medicine","11.30","200","90778",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Lyrica","Medicine","1.80","200","78777",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Meloxicam","Medicine","17.0","200","76766",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Azithromycin","Medicine","91.0","200","76755",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Lorazepam","Medicine","81.0","12","45444",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Ibuprofen","Medicine","41.0","200","86886",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Tramadol","Medicine","16.0","200","46447",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Omeprazole","Medicine","61.0","200","98987",now() + INTERVAL 23 MONTH);
insert into products (product,category,price,quantity,batch_no,expiry_date) values("Lisinopril","Medicine","12.0","200","87778",now() + INTERVAL 23 MONTH);



create user 'pharmacy_admin'@'localhost' identified by 'admin';
Grant all on pharmacy_db.*  to 'pharmacy_admin'@'localhost';
